--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/ReverseTranslation
build-by-default: true
branches:
- master
projects:
  ReverseTranslation:
    path: ""
    icon: "/icon.png"
  libReverseTranslation:
    path: ""
    type: library
    model: virion
...
